# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Tests

on: [ push, pull_request ]

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
        node:
          - 10
          - 12
          - 14

    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }} (Node v${{ matrix.node }})

    steps:
      - uses: actions/checkout@v2
      - name: Setup node 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm run test
